function [TemperatureK, MagneticFieldOe, Bridge1ResistivityOhmm, Bridge2ResistivityOhmm, Bridge3ResistivityOhmm] = LoadResData(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [TEMPERATUREK, MAGNETICFIELDOE, BRIDGE1RESISTIVITYOHMM,
%  BRIDGE2RESISTIVITYOHMM, BRIDGE3RESISTIVITYOHMM] =
%  IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [TEMPERATUREK, MAGNETICFIELDOE, BRIDGE1RESISTIVITYOHMM,
%  BRIDGE2RESISTIVITYOHMM, BRIDGE3RESISTIVITYOHMM] = IMPORTFILE1(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [TemperatureK, MagneticFieldOe, Bridge1ResistivityOhmm, Bridge2ResistivityOhmm, Bridge3ResistivityOhmm] = importfile1("C:\Users\melgazza\OneDrive - George Mason University - O365 Production\Desktop\LAB\TmMn6Sn6-xGax\ACMS\101A_TmMn6Sn6-xGa1p8_MEG1-6A_MR-hall-hall\101A_TmMn6Sn6-xGa1p8_MEG1-6A_MR-hall-hall_RvsH_1p8K.dat", [32, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Jun-2022 19:35:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [32, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "TemperatureK", "MagneticFieldOe", "Var6", "Bridge1ResistivityOhmm", "Var8", "Bridge2ResistivityOhmm", "Var10", "Bridge3ResistivityOhmm", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23"];
opts.SelectedVariableNames = ["TemperatureK", "MagneticFieldOe", "Bridge1ResistivityOhmm", "Bridge2ResistivityOhmm", "Bridge3ResistivityOhmm"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "string", "double", "string", "double", "string", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var6", "Var8", "Var10", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var6", "Var8", "Var10", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
TemperatureK = tbl.TemperatureK;
MagneticFieldOe = tbl.MagneticFieldOe;
Bridge1ResistivityOhmm = tbl.Bridge1ResistivityOhmm;
Bridge2ResistivityOhmm = tbl.Bridge2ResistivityOhmm;
Bridge3ResistivityOhmm = tbl.Bridge3ResistivityOhmm;
end